//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factory
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FactoryEntities : DbContext
    {
        private static FactoryEntities _context;

        public FactoryEntities()
            : base("name=FactoryEntities")
        {
        }
        
        public static FactoryEntities GetContext()
        {
            if (_context == null)
                _context = new FactoryEntities();

            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category_product> Category_product { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Model_clothes> Model_clothes { get; set; }
        public virtual DbSet<Receipt> Receipt { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type_product> Type_product { get; set; }
    }
}
