//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Factory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt
    {
        public int id_receipt { get; set; }
        public int id_model { get; set; }
        public int id_employee { get; set; }
        public System.DateTime date_receipt { get; set; }
        public int amount { get; set; }
    
        public virtual Model_clothes Model_clothes { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
